In [1]:
import pandas as pd
import numpy as np

data_T=pd.read_csv('C://Users//antoi//Dropbox//PC//Desktop//Projet 5//data_T.csv')
data=pd.read_csv('C://Users//antoi//Dropbox//PC//Desktop//Projet 5//data.csv')
X_scaledcv=np.loadtxt('X_scaledcv.csv', delimiter=",")
X_scaledctf=np.loadtxt('X_scaledctf.csv', delimiter=",")
embeddings=np.loadtxt('embeddings.csv', delimiter=",")
features_bert=np.loadtxt('features_bert.csv', delimiter=",")
features_USE=np.loadtxt('features_USE', delimiter=",")

In [2]:
list_of_all_tags = []
for item in data_T['tags']:
    list_of_all_tags.append(item)

tags=np.unique(list_of_all_tags)

In [3]:
tags


array(['.net', 'algorithm', 'android', 'api', 'c', 'c++', 'cocoa', 'com',
       'css', 'date', 'django', 'file', 'git', 'html', 'http', 'image',
       'int', 'ios', 'iphone', 'java', 'jquery', 'linux', 'map', 'memory',
       'multithreading', 'object', 'oop', 'orm', 'other', 'pac', 'php',
       'process', 'python', 'ram', 'ruby', 'spring', 'sql', 'string',
       'testing', 'view', 'visual-studio', 'window', 'xcode'],
      dtype='<U14')

In [4]:
import pickle
import time
from sklearn import cluster, metrics
from sklearn import manifold, decomposition
import logging


logging.disable(logging.WARNING) # disable WARNING, INFO and DEBUG logging everywhere


## Lecture dataset

In [5]:
l_cat = tags.tolist()
print("catégories : ", l_cat)
y_cat_num = [(l_cat.index(data_T['tags'][i])) for i in range(len(data_T))]

catégories :  ['.net', 'algorithm', 'android', 'api', 'c', 'c++', 'cocoa', 'com', 'css', 'date', 'django', 'file', 'git', 'html', 'http', 'image', 'int', 'ios', 'iphone', 'java', 'jquery', 'linux', 'map', 'memory', 'multithreading', 'object', 'oop', 'orm', 'other', 'pac', 'php', 'process', 'python', 'ram', 'ruby', 'spring', 'sql', 'string', 'testing', 'view', 'visual-studio', 'window', 'xcode']


## Fonctions de tests

In [6]:
import pickle
import time
from sklearn import cluster, metrics
from sklearn import manifold, decomposition
import logging
import time
import sklearn.naive_bayes
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# Calcul Tsne, détermination des clusters et calcul ARI entre vrais catégorie et n° de clusters
def ARI_fct_Unsupervised(features) :
    time1 = time.time()
    num_labels=len(l_cat)
    tsne = manifold.TSNE(n_components=2, perplexity=30, n_iter=2000,
                                 init='random', learning_rate=200, random_state=42)
    X_tsne = tsne.fit_transform(features)

    x_train,x_test,y_train,y_test=train_test_split(X_tsne,data_T['tags'].values,test_size=0.25)
    # Détermination des clusters à partir des données après Tsne
    cls = cluster.KMeans(n_clusters=num_labels, n_init=100, random_state=42)
    cls.fit(x_train,y_train)
    ARI = 100*abs(np.round(np.mean(y_test==cls.predict(x_test)),4))
    print(cls.predict(x_test))
    time2 = np.round(time.time() - time1,0)
    print("ARI : ", ARI, "time : ", time2)

    return ARI, X_tsne, cls.labels_

def ARI_fct_bayes(features) :
    time1 = time.time()
    tsne = manifold.TSNE(n_components=2, perplexity=30, n_iter=2000,
                                 init='random', learning_rate=200, random_state=42)
    X_tsne = tsne.fit_transform(features)

    x_train,x_test,y_train,y_test=train_test_split(X_tsne,data_T['tags'].values,test_size=0.25)
    # Détermination des clusters à partir des données après Tsne
    cls = sklearn.naive_bayes.BernoulliNB()
    cls.fit(x_train,y_train)
    ARI = 100*abs(np.round(np.mean(y_test==cls.predict(x_test)),4))
    print(cls.predict(x_test))
    time2 = np.round(time.time() - time1,0)
    print("ARI : ", ARI, "time : ", time2)

    return ARI, X_tsne, cls.classes_, cls

def ARI_fct_DecTree(features) :
    time1 = time.time()
    tsne = manifold.TSNE(n_components=2, perplexity=30, n_iter=2000,
                                 init='random', learning_rate=200, random_state=42)
    X_tsne = tsne.fit_transform(features)

    x_train,x_test,y_train,y_test=train_test_split(X_tsne,data_T['tags'].values,test_size=0.25)
    # Détermination des clusters à partir des données après Tsne
    cls = sklearn.tree.DecisionTreeClassifier()
    cls.fit(x_train,y_train)
    ARI = 100*abs(np.round(np.mean(y_test==cls.predict(x_test)),4))
    print(cls.predict(x_test))
    time2 = np.round(time.time() - time1,0)
    print("ARI : ", ARI, "time : ", time2)

    return ARI, X_tsne, cls.classes_, cls


def ARI_fct_KNeighbors(features) :
    time1 = time.time()
    num_labels=len(l_cat)
    tsne = manifold.TSNE(n_components=2, perplexity=30, n_iter=2000,
                                 init='random', learning_rate=200, random_state=42)
    X_tsne = tsne.fit_transform(features)

    x_train,x_test,y_train,y_test=train_test_split(X_tsne,data_T['tags'].values,test_size=0.25)
    # Détermination des clusters à partir des données après Tsne
    cls = sklearn.neighbors.KNeighborsClassifier(n_neighbors=num_labels)
    cls.fit(x_train,y_train)
    ARI = 100*abs(np.round(np.mean(y_test==cls.predict(x_test)),4))
    print(cls.predict(x_test))
    time2 = np.round(time.time() - time1,0)
    print("ARI : ", ARI, "time : ", time2)

    return ARI, X_tsne, cls.classes_, cls

def ARI_fct_Forest(features) :
    time1 = time.time()
    tsne = manifold.TSNE(n_components=2, perplexity=30, n_iter=2000,
                                 init='random', learning_rate=200, random_state=42)
    X_tsne = tsne.fit_transform(features)

    x_train,x_test,y_train,y_test=train_test_split(X_tsne,data_T['tags'].values,test_size=0.25)
    # Détermination des clusters à partir des données après Tsne
    cls = sklearn.ensemble.RandomForestClassifier()
    cls.fit(x_train,y_train)
    ARI = 100*abs(np.round(np.mean(y_test==cls.predict(x_test)),4))
    print(cls.predict(x_test))
    time2 = np.round(time.time() - time1,0)
    print("ARI : ", ARI, "time : ", time2)

    return ARI, X_tsne, cls.classes_, cls


# visualisation du Tsne selon les vraies catégories et selon les clusters
def TSNE_visu_fct(X_tsne, y_cat_num, labels, ARI) :
    fig = plt.figure(figsize=(15,6))

    ax = fig.add_subplot(121)
    scatter = ax.scatter(X_tsne[:,0],X_tsne[:,1], c=y_cat_num, cmap='Set1')
    ax.legend(handles=scatter.legend_elements()[0], labels=l_cat, loc="best", title="Categorie")
    plt.title('Représentation des tags par catégories réelles')

    ax = fig.add_subplot(122)
    scatter = ax.scatter(X_tsne[:,0],X_tsne[:,1], c=labels, cmap='Set1')
    ax.legend(handles=scatter.legend_elements()[0], labels=set(labels), loc="best", title="Clusters")
    plt.title('Représentation des tags par clusters')

    plt.show()
    print("ARI : ", ARI)

In [7]:
scores=pd.DataFrame(columns=['CountVectorized','Tf-idf','Word2Vec','BERT','USE'],index=['Unsuppervised','NaiveBayes','DecisionTree','KNeighbours','RandomForest'])

# Unsuppervised

In [8]:
ARI, X_tsne, labels=ARI_fct_Unsupervised(X_scaledcv)
scores['CountVectorized']['Unsuppervised']=ARI

[39 14 11 ...  5 37 28]
ARI :  0.0 time :  38.0


In [9]:
ARI, X_tsne, labels=ARI_fct_Unsupervised(X_scaledctf)
scores['Tf-idf']['Unsuppervised']=ARI

[31 29 39 ... 30  4 38]
ARI :  0.0 time :  35.0


In [10]:
ARI, X_tsne, labels=ARI_fct_Unsupervised(embeddings)
scores['Word2Vec']['Unsuppervised']=ARI

[18 27  3 ... 25 15 31]
ARI :  0.0 time :  29.0


In [11]:
ARI, X_tsne, labels=ARI_fct_Unsupervised(features_bert)
scores['BERT']['Unsuppervised']=ARI

[23 29 20 ... 20 30 41]
ARI :  0.0 time :  28.0


In [12]:
ARI, X_tsne, labels=ARI_fct_Unsupervised(features_USE)
scores['USE']['Unsuppervised']=ARI

[16 27 18 ... 36  8 32]
ARI :  0.0 time :  25.0


# CountVectorizer

In [13]:
print("CountVectorizer : ")
print("-----------------")
ARI, X_tsne, labels, cls = ARI_fct_bayes(X_scaledcv)
print()
scores['CountVectorized']['NaiveBayes']=ARI

CountVectorizer : 
-----------------
['other' 'other' 'other' ... 'other' 'other' 'other']
ARI :  20.48 time :  29.0



In [14]:
print("CountVectorizer : ")
print("-----------------")
ARI, X_tsne, labels, cls = ARI_fct_DecTree(X_scaledcv)
print()
scores['CountVectorized']['DecisionTree']=ARI

CountVectorizer : 
-----------------
['iphone' 'other' 'other' ... 'c' 'other' 'c']
ARI :  12.24 time :  29.0



In [15]:
print("CountVectorizer : ")
print("-----------------")
ARI, X_tsne, labels, cls = ARI_fct_KNeighbors(X_scaledcv)
print()
scores['CountVectorized']['KNeighbours']=ARI

CountVectorizer : 
-----------------
['other' 'java' 'other' ... 'c' 'other' 'java']
ARI :  19.439999999999998 time :  29.0



In [16]:
print("CountVectorizer : ")
print("-----------------")
ARI, X_tsne, labels, cls = ARI_fct_Forest(X_scaledcv)
print()
scores['CountVectorized']['RandomForest']=ARI

CountVectorizer : 
-----------------
['memory' 'django' 'php' ... 'linux' 'jquery' 'c']
ARI :  14.399999999999999 time :  29.0



# Tf-idf

In [17]:
print("Tf-idf : ")
print("--------")
ARI, X_tsne, labels, cls = ARI_fct_bayes(X_scaledctf)
scores['Tf-idf']['NaiveBayes']=ARI

Tf-idf : 
--------
['other' 'other' 'other' ... 'other' 'other' 'other']
ARI :  21.759999999999998 time :  29.0


In [18]:
print("Tf-idf : ")
print("--------")
ARI, X_tsne, labels, cls = ARI_fct_DecTree(X_scaledctf)
scores['Tf-idf']['DecisionTree']=ARI

Tf-idf : 
--------
['iphone' 'jquery' 'php' ... 'ios' 'c++' 'python']
ARI :  11.12 time :  29.0


In [19]:
print("Tf-idf : ")
print("--------")
ARI, X_tsne, labels, cls = ARI_fct_KNeighbors(X_scaledctf)
scores['Tf-idf']['KNeighbours']=ARI

Tf-idf : 
--------
['other' 'other' 'other' ... 'other' 'other' 'c']
ARI :  19.36 time :  29.0


In [20]:
print("Tf-idf : ")
print("--------")
ARI, X_tsne, labels, cls = ARI_fct_Forest(X_scaledctf)
scores['Tf-idf']['RandomForest']=ARI

Tf-idf : 
--------
['other' 'python' 'sql' ... 'ios' 'c' 'other']
ARI :  16.32 time :  30.0


## Exécution du modèle



In [21]:
ARI, X_tsne, labels, cls = ARI_fct_bayes(embeddings)
scores['Word2Vec']['NaiveBayes']=ARI

['c' 'other' 'other' ... 'other' 'other' 'other']
ARI :  22.16 time :  24.0


In [22]:
ARI, X_tsne, labels, cls = ARI_fct_DecTree(embeddings)
scores['Word2Vec']['DecisionTree']=ARI

['iphone' 'other' 'git' ... 'oop' 'java' 'java']
ARI :  26.479999999999997 time :  24.0


In [23]:
ARI, X_tsne, labels, cls = ARI_fct_KNeighbors(embeddings)
scores['Word2Vec']['KNeighbours']=ARI

['c' 'other' 'python' ... 'java' 'c' 'c++']
ARI :  28.08 time :  25.0


In [24]:
ARI, X_tsne, labels, cls = ARI_fct_Forest(embeddings)
scores['Word2Vec']['RandomForest']=ARI

['jquery' 'jquery' 'jquery' ... 'other' 'other' 'string']
ARI :  30.959999999999997 time :  25.0


# BERT

In [25]:
ARI, X_tsne, labels, cls = ARI_fct_bayes(features_bert)
scores['BERT']['NaiveBayes']=ARI

['other' 'other' 'other' ... 'other' 'other' 'other']
ARI :  20.72 time :  23.0


In [26]:
ARI, X_tsne, labels, cls = ARI_fct_DecTree(features_bert)
scores['BERT']['DecisionTree']=ARI

['other' 'other' 'ios' ... 'jquery' 'c++' 'c++']
ARI :  18.64 time :  22.0


In [27]:
ARI, X_tsne, labels, cls = ARI_fct_KNeighbors(features_bert)
scores['BERT']['KNeighbours']=ARI

['c' 'sql' 'other' ... 'java' 'other' 'other']
ARI :  22.720000000000002 time :  23.0


In [28]:
ARI, X_tsne, labels, cls = ARI_fct_Forest(features_bert)
scores['BERT']['RandomForest']=ARI

['iphone' 'c++' 'c' ... 'java' 'python' 'iphone']
ARI :  23.84 time :  23.0


# USE

In [29]:
ARI, X_tsne, labels, cls = ARI_fct_bayes(features_USE)
scores['USE']['NaiveBayes']=ARI

['other' 'ios' 'ios' ... 'other' 'ios' 'ios']
ARI :  22.24 time :  21.0


In [30]:
ARI, X_tsne, labels, cls = ARI_fct_DecTree(features_USE)
scores['USE']['DecisionTree']=ARI

['.net' 'algorithm' 'java' ... 'android' 'other' 'iphone']
ARI :  41.839999999999996 time :  22.0


In [31]:
ARI, X_tsne, labels, cls = ARI_fct_KNeighbors(features_USE)
scores['USE']['KNeighbours']=ARI

['c' 'other' 'java' ... 'other' 'python' 'c']
ARI :  43.36 time :  22.0


In [32]:
ARI, X_tsne, labels, cls = ARI_fct_Forest(features_USE)
scores['USE']['RandomForest']=ARI

['python' 'other' 'c' ... 'other' 'python' 'jquery']
ARI :  47.68 time :  23.0


In [33]:
scores

CountVectorized Tf-idf Word2Vec   BERT    USE
Unsuppervised             0.0    0.0      0.0    0.0    0.0
NaiveBayes              20.48  21.76    22.16  20.72  22.24
DecisionTree            12.24  11.12    26.48  18.64  41.84
KNeighbours             19.44  19.36    28.08  22.72  43.36
RandomForest             14.4  16.32    30.96  23.84  47.68